### ISSUE TITLE
404 Message when trying to download retroBenny Themes through Theme master

### ISSUE THREAD

**Issue by TheBenny** [Jetup13/Emulationstation-OGA-Theme-Gallery#3]
Hey so I just tried downloading some of my retro benny themes from thememaster and for 

1. they dont show up in thememaster when its on GitHub repository mode,
2. On theme gallery mode they show up, but when i try and install them i get a 404 message. This is because the api.github.com/repos//es-theme-RG351V-RetroBenny... should not have "es-theme-" in it. It just starts with RG351V

**Comment by Jetup13** [comment]
Whoops my bad, seems like Thememaster will only look for [es-themes-](https://github.com/JohnIrvine1433/ThemeMaster#github-repository-mode) regardless of mode. I thought this was bypassed when in gallery mode but that doesn't seem like case. Try adding `es-theme-` to each of your themes and that should fix it.

**Comment by TheBenny** [comment]
should be fixed now ive added it to each of the repositories, though on theme gallery github you may need to add "es-theme-" to each of the theme links

**Comment by TheBenny** [comment]
Hey im still getting that 404 message even though ive renamed them to include es-theme-
here is a photo of the error https://imgur.com/a/pmI3rWc

**Comment by Jetup13** [comment]
It's working. Switch modes and switch back to gallery mode for Thememaster to update the cache.
Double-checked I was able to download all 5 of the themes

**Comment by TheBenny** [comment]
ok sweet!
